const stage = document.getElementById('stage'), grade = document.getElementById('grade');
const grades = {'ابتدائية':['الأول الابتدائي','الثاني الابتدائي','الثالث الابتدائي','الرابع الابتدائي','الخامس الابتدائي','السادس الابتدائي'],'إعدادية':['الأول الإعدادي','الثاني الإعدادي','الثالث الإعدادي'],'ثانوية':['الأول الثانوي','الثاني الثانوي','الثالث الثانوي']};
stage?.addEventListener('change',()=>{grade.innerHTML='<option value="">اختار الصف</option>';(grades[stage.value]||[]).forEach(g=>grade.insertAdjacentHTML('beforeend',`<option>${window.ELR.escape(g)}</option>`));grade.disabled=!stage.value;});
function msg(t,ok=false){const e=document.getElementById('authMsg');if(e){e.textContent=t;e.className='auth-msg '+(ok?'ok':'bad');}}
function passOK(p){return p.length>=8&&/[A-Z]/.test(p)&&/[a-z]/.test(p)&&/\d/.test(p)&&/[^A-Za-z0-9]/.test(p)}
async function ready(){if(!window.elrfaeySupabase){msg('ضع Project URL و Publishable/anon key في js/supabase-config.js');return false}return true}
let pendingPhone = null;
document.getElementById('registerForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!(await ready()))return;const name=document.getElementById('fullName').value.trim(),phone=window.normalizeEgyptianPhone(document.getElementById('phone').value),p=document.getElementById('password').value;if(!name||!stage.value||!grade.value){msg('اكمل البيانات المطلوبة.');return}if(!/^\+20(10|11|12|15)\d{8}$/.test(phone)){msg('اكتب رقم موبايل مصري صحيح.');return}if(!passOK(p)){msg('كلمة السر: 8 أحرف على الأقل + حرف كبير + حرف صغير + رقم + رمز.');return}msg('جاري إنشاء الحساب...');const {data,error}=await window.elrfaeySupabase.auth.signUp({phone,password:p,options:{data:{full_name:name,stage:stage.value,grade:grade.value}}});if(error){console.error(error);msg('لم يتم إنشاء الحساب: '+(error.message||'خطأ غير معروف'));return}if(data.session){msg('تم إنشاء الحساب وتسجيل الدخول.',true);location.href='dashboard.html'}else{pendingPhone=phone;const box=document.getElementById('otpBox');if(box)box.hidden=false;msg('تم إرسال كود التحقق على الهاتف. اكتب الكود بالأسفل لإكمال التسجيل.',true)}});
document.getElementById('verifyOtp')?.addEventListener('click',async()=>{const code=document.getElementById('otpCode')?.value.trim();if(!pendingPhone||!code){msg('اكتب كود التحقق أولًا.');return}msg('جاري التحقق...');const {data,error}=await window.elrfaeySupabase.auth.verifyOtp({phone:pendingPhone,token:code,type:'sms'});if(error){console.error(error);msg('كود التحقق غير صحيح أو انتهت صلاحيته.');return}msg('تم تأكيد الحساب بنجاح.',true);location.href='dashboard.html'});
document.getElementById('loginForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!(await ready()))return;const phone=window.normalizeEgyptianPhone(document.getElementById('loginUser').value),password=document.getElementById('loginPass').value;if(!/^\+20(10|11|12|15)\d{8}$/.test(phone)){msg('رقم الهاتف غير صحيح.');return}const {data,error}=await window.elrfaeySupabase.auth.signInWithPassword({phone,password});if(error){console.error(error);msg('بيانات الدخول غير صحيحة أو الحساب غير مؤكد.');return}location.href=new URLSearchParams(location.search).has('admin')?'../admin/index.html':'dashboard.html'});
